pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git branch: 'Dev', url: 'https://github.com/yourusername/final-project-web-app.git'
            }
        }
        stage('Build Docker Image') {
            steps {
                script {
                    dockerImage = docker.build("yourdockerhubusername/final-project-web-app:latest")
                }
            }
        }
        stage('Push Docker Image') {
            steps {
                script {
                    docker.withRegistry('https://registry.hub.docker.com', 'dockerhub-credentials') {
                        dockerImage.push()
                    }
                }
            }
        }
        stage('Deploy to Kubernetes') {
            steps {
                script {
                    kubectl.apply('-f deployment.yaml')
                    kubectl.apply('-f service.yaml')
                }
            }
        }
    }
}
