- hosts: ec2
  become: yes
  tasks:
    - name: Update apt packages
      apt:
        update_cache: yes

    - name: Install Java (Jenkins requires Java)
      apt:
        name: openjdk-11-jdk
        state: present

    - name: Add Jenkins repository key to the system
      apt_key:
        url: https://pkg.jenkins.io/debian/jenkins.io.key
        state: present

    - name: Add Jenkins repository
      apt_repository:
        repo: 'deb http://pkg.jenkins.io/debian-stable binary/'
        state: present

    - name: Install Jenkins
      apt:
        name: jenkins
        state: present

    - name: Start Jenkins service
      systemd:
        name: jenkins
        state: started
        enabled: true

    - name: Ensure Jenkins is running
      systemd:
        name: jenkins
        state: started
